### PR TITLE
compress files in virtual file system (#885)

### LINKED ISSUE #885: Zip executables ?
Can we have an option like  `--zip` to compress executables as soon as they are built 🤔

### PR DESCRIPTION
**Pull request by erossignon**
Fixes #885

### CODE REVIEW

**Comment by hipstersmoothie** [comment]
Would be cool to see some before and after data on this

**Comment by erossignon** [comment]
This PR enables compression of Virtual File System table and Zip/Brotli compression of each individual file content.
This allows a gain of up to 60% of the embedded file system.


```` 
node.exe size  = 71917203
No compression =  175703
        Δ GZip =  -100540 ( -57 %)
      Δ Brotli =  -109057 ( -62 %)
````

**Comment by jesec** [comment]
If possible, IMO we can try to make it possible to compress the entire binary, not only the virtual file system.

**Comment by robertsLando** [comment]
@erossignon Nice work here! BTW I have linked the pr that was asking for zip executables, what do you think about them? I know https://www.npmjs.com/package/caxa works in this way for example

**Comment by erossignon** [comment]
> If possible, IMO we can try to make it possible to compress the entire binary, not only the virtual file system.

Yes, The executable that we use from pkg_fetch is far too big, It should be compiled with minimum ICU to significantly reduce its size. then we could had some options in pkg to reference or add the ICU as a external module ( optional)

I have no idea how to compress the entire executable further... if you have a idea, let me know.

**Comment by robertsLando** [comment]
@erossignon caxa does this, more info in the repo: https://github.com/leafac/caxa#readme

**Review by robertsLando — APPROVED** [review]
LGTM.

cc @leerob @jesec

**Comment by erossignon** [comment]
@leerob @jesec , do you have any objection that would prevent merging  ?

**Comment by leerob** [comment]
I'd like to wait until we cut a release of pkg that's fetching from pkg-fetch properly.

**Comment by erossignon** [comment]
> I'd like to wait until we cut a release of pkg that's fetching from pkg-fetch properly.

OK, I'll keep rebasing and keep the code up to date until new version of pkg-fetch is fully integrated

**Comment by Hypfer** [comment]
> I have no idea how to compress the entire executable further... if you have a idea, let me know.

[UPX](https://github.com/upx/upx) might be an option

See:
https://github.com/vercel/pkg/issues/50#issuecomment-789951164

Relevant quotes

> https://sourceforge.net/p/upx/discussion/6806/thread/79e2a6b8/

> As it is now, the `readPrelude` function patched into the nodejs binary will open `/proc/self/exe` and try reading the overlay from the offset replaced into the binary at packaging time. However since the binary found at `/proc/self/exe` is the compressed version, all those offsets are of course just wrong and even if they weren't they would still read compressed data.

> To get pkg to work with upx, one approach could be to update the `readPrelude` function so that it uses relative offsets from the end of the file and extend the pkg process so that it first bakes in the commandline options, then packs that binary and finally appends the rest of the code.

**Comment by erossignon** [comment]
@leerob  can we incorporated to a 5.1  release ?

**Comment by leerob** [comment]
5.1 is out, but we can get this in 5.2! 😁

**Comment by alitas** [comment]
On an unrelated note, there seems to be a typo on a few lines in the commits, both in code and documentation, using Brolti instead of Brotli. It might cause some confusion among users.

**Comment by robertsLando** [comment]
@erossignon Could you fix the typos?

**Comment by erossignon** [comment]
let's go

**Comment by Hypfer** [comment]
When testing this + upx, my webserver spontaneusly started to deliver compressed assets
image

This may or may not be a side-effect of the upx compression though

**Comment by robertsLando** [comment]
@jesec @leerob Could we merge this?

**Comment by erossignon** [comment]
>  It did work fine initially and only stopped working after a few minutes of runtime

This could mean  that the size of the executable could changed at runtime somehow ?! your technique for relative offset, reads the executable size each time to find the start of the prelude by subtracting the payload size. Strange.

**Pull request merged**
