### PR TITLE
chore: separate individual test scripts

### PR DESCRIPTION
**Pull request by ignatiusmb**
This will make running test script individually possible

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]

**Comment by robertsLando** [comment]
@ignatiusmb please merge master into this branch, otherwise I cannot merge it

**Comment by ignatiusmb** [comment]
Noted, thanks for the info

**Review by robertsLando — APPROVED** [review]

**Comment by robertsLando** [comment]
One test is failing

**Comment by ignatiusmb** [comment]
I think that one's a flake (?) the merge commit was added cleanly, and the changes here only extracts the test scripts out. Hopefully the other tests passed successfully.

**Pull request merged**
