### PR TITLE
Update links to Vercel

### PR DESCRIPTION
**Pull request by sarupbanskota**

### CODE REVIEW

**Comment by Jacob-Marshall** [comment]
@sarupbanskota I know these changes weren’t implemented when you made the pull request, but they have been since.

Thanks, Jacob

**Comment by igorklopov** [comment]
I suggest merging this one. Wdyt @Jacob-Marshall

**Comment by Jacob-Marshall** [comment]
@igorklopov Okay cool but we will have to resolve the conflict first

**Comment by Jacob-Marshall** [comment]
@igorklopov Can I have write access to merge?

**Comment by leerob** [comment]
Not needed anymore!

**Pull request closed without merging**
