### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by KillWolfVlad**
Would be great to have types with this :)

### CODE REVIEW

**Comment by leerob** [comment]
Hey! I'd be willing to merge types if this was a complete PR. If you'd like to contribute back and open an issue / PR, I'd be happy to review.

**Comment by KillWolfVlad** [comment]
@leerob Hey! Why this PR is not complete? What is missing and what should be added?

**Comment by leerob** [comment]
Wouldn't all of the API options need to be typed, ideally?

https://github.com/vercel/pkg#api

**Comment by KillWolfVlad** [comment]
@leerob Yes, that would be great. But I doubt TypeScript supports that. Can we start with simple types? I think even simple types will be useful to many.

**Comment by leerob** [comment]
Let's continue the discussion here and gauge community interest https://github.com/vercel/pkg/issues/678

**Pull request closed without merging**
