### PR TITLE
fix: catch babel parse errors

### LINKED ISSUE #746: [bug] Ignore .vue files inside node_modules
I'm getting this error

```
> Error! Unexpected token (3:0)
  /myApp/node_modules/vue2-google-maps/dist/components/infoWindow.vue
```

Seems that pkg is trying to compile a vue files and this throws the error shown. How can  this be avoided?

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #746

### CODE REVIEW

**Comment by robertsLando** [comment]
> We should find out why pkg tries to parse a .vue file.

I haven't been able to detect where this happens, maybe because It try to parse assets somewhere, BTW this could be a temporary fix until we find a better solution?

**Comment by jesec** [comment]
I am worried about the risk that the real errors got ignored.

**Comment by robertsLando** [comment]
Maybe I could add a log so at least users know something has fail?

**Comment by jesec** [comment]
Yeah. We can downgrade it (from error) to warning for the time being.

**Comment by robertsLando** [comment]
@jesec Could we also merge this?

**Comment by robertsLando** [comment]
Strange the eslint didn't catch them on CI (and also on my editor) 😕 BTW it's fixed now

**Pull request merged**
