### PR TITLE
feat: allow to specify custom babel plugins

### PR DESCRIPTION
**Pull request by robertsLando**
This can easily be done using `PKG_BABEL_PLUGINS` env var

### CODE REVIEW

**Comment by jesec** [comment]
Hmmm... We definitely don't want to have more env variables. 

Additionally, any Babel plugins have to be in the dependency (node_modules) tree of `pkg`. It is improbable to add them all as dependencies. 

Users should not run pkg on an entrypoint that's otherwise not runnable on Node.js runtime without transpilation. Users should run the transpilation first and then run pkg.

Thus, additional Babel plugins are definitely out-of-scope for pkg, and I don't think we can move forward in any way with this idea.

**Comment by robertsLando** [comment]
@jesec In my case I needed to add `'classPrivateMethods'` and it doesn't require a plugin to be installed. It is used by a module of my application. Should I add that to babel plugins by hardcoding it? 

BTW I don't see any issue in adding env vars, they just add advanced functionalities to the application, them are not intended to be used by all users

**Comment by jesec** [comment]
> @jesec In my case I needed to add `'classPrivateMethods'` and it doesn't require a plugin to be installed. It is used by a module of my application. Should I add that to babel plugins by hardcoding it here so?
> 
> BTW I don't see any issue in adding env vars, they just add advanced functionalities to the application, them are not intended to be used by all users

See https://github.com/vercel/pkg/pull/1249#issuecomment-1111543386.

Unless we want to diverge from this, we can't have additional Babel plugins. 

I am open to discussion about this, though. It might make some sense to shift the burden of the correctness check to users. In that case, we can use `preset/env` with `targets.node` set to the latest Node supported by us.

**Comment by robertsLando** [comment]
> we can use preset/env with targets.node set to the latest Node supported by us.

How can we do this so?

**Pull request closed without merging**
