### PR TITLE
fix: do not overwrite temp .node files

### PR DESCRIPTION
**Pull request by paul-marechal**
This can happen when two processes try to load the same .node file.

### CODE REVIEW

**Comment by paul-marechal** [comment]
The `CI / test` failures seem unrelated?

**Comment by jesec** [comment]
See #1492 .

**Comment by paul-marechal** [comment]
@jesec I know about https://github.com/vercel/pkg/pull/1492, and there the issue happened because it used to check for the _folder_ to exist, and I can anecdotally say that I also encountered the same issue in the past where the folder would exist but the `.node` file would be missing.

This PR is different because it checks for the file's existence.

**Review by robertsLando — APPROVED** [review]
@jesec I agree, the other PR is for the first if case where the entire folder is copied

**Review by jesec — APPROVED** [review]

**Comment by robertsLando** [comment]
Can this be merged?

**Pull request merged**
