### PR TITLE
fix: pick up the correct file argument when forking a process

### LINKED ISSUE #459: Unable to use baked runtime options in forked scripts
## The problem:

If you write a simple script that forks, and set max_old_space_size, pkg will fail with:
> Error: Cannot find module '--max_old_space_size=4096'

This works fine when running directly from node (node --max-old-space-size=4092 index.js). It is related to #334. If you comment out the fork line, pkg will successfully set the parameter for index.js, but of course then forking is disabled.

## Steps to reproduce:
index.js:
```javascript
const v8 = require('v8');
const path = require('path');
const { fork } = require('child_process');
fork(path.join(__dirname, 'forked.js'));
// if you compile without --options max_old_space_size, this will also fail with the same error:
//fork(path.join(__dirname, 'forked.js'), [], {
//    execArgv: ['--max_old_space_size=4092'],
//});
console.log('parent execArgv', process.execArgv);
console.log('parent heap', v8.getHeapStatistics());
```
forked.js:
```javascript
const v8 = require('v8');
console.log('forked execArgv', process.execArgv);
console.log('forked heap', v8.getHeapStatistics());
```
package.json:
```json
{
  "name": "fork",
  "bin": "index.js",
  "pkg": {
    "targets": [
      "node10"
    ]
  }
}

```
Compiled and run like this:
`pkg --options max_old_space_size=4096 . && ./fork`

...using pkg@4.3.3 installed using node 10.4.1.

### LINKED ISSUE #1461: multi-process(cluster) not working with v8 options?
### What version of pkg are you using?

5.5.1

### What version of Node.js are you using?

v12.22.8

### What operating system are you using?

centos7

### What CPU architecture are you using?

x86_64 & arm64

### What Node versions, OSs and CPU architectures are you building for?

node12-linux

### Describe the Bug
Program run in Muti-process mode,   pkg with --options (v8) , app run error
Simple test code:
```js
const cluster = require('cluster');
if (cluster.isMaster) {
    for (let i = 0; i < 2; i++)
        cluster.fork();
}
else if (cluster.isWorker){
    console.log("Create worker_%d(%d)", cluster.worker.id, process.pid);
}
```
package it with v8-options:
```bash
pkg -t linux index.js  --options max-old-space-size=3072
```

when app run, error:
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/git/test/--max-old-space-size=3072'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1847:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

PS
```
I also test with the node V16.13.1,    same error
```

### Expected Behavior

run fine in multi-process mode

### To Reproduce

As decribe

### PR DESCRIPTION
**Pull request by robertsLando**
This enables you to fork a process with run time arguments, for instance
--max_old_space_size=1024.

This is an old fix by @bergheim. Never submitted a PR for it

Fixes #459 
Fixes #1461

### CODE REVIEW

**Comment by bergheim** [comment]
Awesome! I really thought I had submitted this and that it was just ignored.

I am still using it, and I believe I have rebased a bit etc because I am on master. Must not have updated github. Will have a look over the new year and update this.

**Comment by robertsLando** [comment]
@bergheim Yeah please fix merge conflicts so we can merge this :)

**Comment by robertsLando** [comment]
cc @jesec

**Comment by jesec** [comment]
Tests are failing.

**Comment by bergheim** [comment]
Hello,

I tried to add this as a PR but that was already here (I now remember), so I guess we can just keep it here. Tests pass, and it works fine for me with various mem settings and forking, but I suspect something is still off with this old code.

I wrote some tests. However getting runtime options into https://github.com/bergheim/pkg/blob/fa0b1a478bbf618a0ca23a6028249bfffa572e8f/test/utils.js#L120 was a bit tricky given the time I had. I want to pass `execArgv` to `utils.pkg.sync`. But I am unable to get anything into ~left~ args in the test. Any pointers?

Thanks.

**Comment by robertsLando** [comment]
Sorry I dunno how to help here, maybe @jesec?

**Comment by robertsLando** [comment]
Looks good to me overall. Would like to also have @jesec opinion. 

Could you add a test too?

**Comment by robertsLando** [comment]
@jesec Ping

**Comment by faroceann** [comment]
looks like @jesec hasn't been very active in this repo @robertsLando

**Comment by robertsLando** [comment]
@faroceann Unfortunately I haven't the privileges to do so much, I could merge this but I wouldn't be able to create releases. I will try to ping @jesec via PM but I know he has been very full in last months

**Comment by robertsLando** [comment]
@baparham Also may have sense to merge this too before next release

**Comment by baparham** [comment]
I guess the todo's left here are:

- [ ] Rebase against latest main, resolve any conflicts
- [ ] add a test (how? seems difficult considering @bergheim previous comments)

**Comment by jromero-pg** [comment]
@leerob do you know who can provide some feedback on this PR and/or get it merged?

**Pull request closed without merging**
