### PR TITLE
Drop dependabot.yml to only support security updates

### PR DESCRIPTION
**Pull request by robertsLando**
@jesec @leerob

### CODE REVIEW

**Review by jesec — APPROVED** [review]
lg2m. Other parts of the file use single quote (`'`), though.

**Comment by robertsLando** [comment]
@jesec You wight didn't noticed that. BTW dependabot is failing to parse the new configuration, let me check it

**Comment by robertsLando** [comment]
Seems that was the old way to handle security updates, now this needs to be handled in [repo settings](https://docs.github.com/en/code-security/supply-chain-security/configuring-dependabot-security-updates). I suggest @leerob to drop dependabot file and make the changes explained in the link

**Review by leerob — APPROVED** [review]

**Comment by leerob** [comment]
image
They're now on!

**Pull request merged**
