### PR TITLE
prebuild improvements

### PR DESCRIPTION
**Pull request by mojoaxel**
- fix: remove dot-net backup file

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by jesec** [comment]
@mojoaxel I can't rebase for you unfortunately. Please allow maintainers to make changes to the PR.

**Comment by mojoaxel** [comment]
> @mojoaxel I can't rebase for you unfortunately. Please allow maintainers to make changes to the PR.

Looks like I can't change maintainers access after creating the PR. Sorry for that! Feel free to cherry-pick my commits!

**Comment by jesec** [comment]
> > @mojoaxel I can't rebase for you unfortunately. Please allow maintainers to make changes to the PR.
> 
> Looks like I can't change maintainers access after creating the PR. Sorry for that! Feel free to cherry-pick my commits!

Great. Please take a took at #1208 when you have time.

**Comment by jesec** [comment]
Landed: 80103ddeb85786548726c8c71b348d053d21e991.

**Pull request closed without merging**
