### PR TITLE
Bump to vercel/pkg-fetch@v3.0

### PR DESCRIPTION
**Pull request by jesec**

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by pablitovicente** [comment]
Is there an upcoming PR that uses pkg-fetch 3.0.1 (https://github.com/vercel/pkg-fetch/releases/tag/3.0.1) that seems is the one to include the latest v12 and v14 versions of Node or should the package.lock and yarn.lock in this PR use pkg-fetch 3.0.1?

**Comment by leerob** [comment]
Yes!

**Comment by jesec** [comment]
It is passing. We can do a new major `pkg` release with this PR merged.

However, I think we should discuss vercel/pkg-fetch#164 before we do that, as that could involve breaking changes, and we would want to make necessary breaking changes before the new major release.

**Review by robertsLando — APPROVED** [review]
LGTM

**Comment by jesec** [comment]
Merging. But don’t rush to release, yet.

**Comment by pvenkatesh** [comment]
Any schedule to release pkg with this patch/update?

**Comment by robertsLando** [comment]
soon

**Comment by vweevers** [comment]
Is this (dropping node < 8) the only breaking change in [5.0.0](https://github.com/vercel/pkg/releases/tag/5.0.0)?

**Pull request merged**
