### PR TITLE
Add docs for automatic releases w. GitHub Actions

### PR DESCRIPTION
**Pull request by karlhorky**
Hi there, thanks for `pkg`, really amazing!

Wanted to test the waters on documenting usage of GitHub actions to automate building using `pkg` and uploading the executables as assets to a GitHub release.

Example here:

- Workflow: https://github.com/jonaschlegel/lgo-agisoft-converter/blob/main/.github/workflows/release.yml
- Release: https://github.com/jonaschlegel/lgo-agisoft-converter/releases/tag/v1.0.0

### CODE REVIEW

**Comment by jesec** [comment]
Thanks for the contribution. It is a very good tutorial.

Unfortunately, it would be inappropriate for us to endorse a specific CI service.

Additionally, naturally people assume that project maintainers provide support to contents in README of the project. However, we do not have the capacity to support Github Actions, and we will not be able to answer everyone's (in our view, out-of-scope) "how to automate my workflow" questions. 

In fact, there are many other ways to integrate `pkg` with the workflow of the project. A way that does not tie to a specific CI provider is to simply add a "build-pkg` command to `package.json`, so anyone (incl. any CI provider one may choose) can run `npm run build-pkg` to build the pkg executables.

**Comment by karlhorky** [comment]
Ah ok, would it be accepted if there were examples for other CI platforms? Also with a disclaimer that there is no support provided for this?

The value that I see is in the ability of copy + pasting this without having to research the different parts and how to plug them together (which can take hours)

**Comment by jesec** [comment]
> Ah ok, would it be accepted if there were examples for other CI platforms? Also with a disclaimer that there is no support provided for this?
> 
> The value that I see is in the ability of copy + pasting this without having to research the different parts and how to plug them together (which can take hours)

That kinda makes things worse, and we are now expected to provide support to not only Github Actions but also others. 

Well. We all know that people don't read disclaimer. ;) 

If things are in README, we are expected to provide (some degree of) support. I do not believe that we should do that, and we don't have resources for that. "How to automate your workflow" is quite out-of-scope for this project.

**Comment by karlhorky** [comment]
Ok, then how about an `examples` or `recipes` folder, à la Next.js? Those are very clearly maintained by community members.

**Comment by jesec** [comment]
> Ok, then how about an `examples` or `recipes` folder, à la Next.js? Those are very clearly maintained by community members.
> 
> Then the readme could link to this examples folder...

That would be a bit more acceptable. 

Keep in mind that Next.js is the main product and is maintained by a team of dedicated engineers. This project is not allocated the same level of resources and is mostly maintained in voluntary capacity. 

I believe that such out-of-scope tutorials/examples do not necessarily justify the maintenance burden, as a result.

**Comment by karlhorky** [comment]
Ok, would such a PR be accepted? If not, then we can just leave it at that.

**Comment by jesec** [comment]
> Ok, would such a PR be accepted? If not, then we can just leave it at that.

Unfortunately, no.

**Comment by azerpas** [comment]
> Hi there, thanks for `pkg`, really amazing!
> 
> Wanted to test the waters on documenting usage of GitHub actions to automate building using `pkg` and uploading the executables as assets to a GitHub release.
> 
> Example here:
> 
> * Workflow: https://github.com/jonaschlegel/lgo-agisoft-converter/blob/main/.github/workflows/release.yml
> * Release: https://github.com/jonaschlegel/lgo-agisoft-converter/releases/tag/v1.0.0

Great example, thanks!

**Comment by karlhorky** [comment]
@azerpas glad that it helped you!

Since it unfortunately won't be accepted here, I have published a separate repo with the guide: https://github.com/karlhorky/vercel-pkg-github-actions-release

**Pull request closed without merging**
