### PR TITLE
Recursive reference without node

### PR DESCRIPTION
**Pull request by aboe026**
Allow the pkg binary to be called within itself without adjusting process.argv as if it were a node process.

### CODE REVIEW

**Comment by aboe026** [comment]
I believe this is somewhat related to https://github.com/vercel/pkg/issues/376

**Comment by aboe026** [comment]
Also some guidance on tests would be helpful. For instance, I'm not sure what the test numbers mean, and they also seems to contain a mix of PR numbers and issue numbers.

**Review by robertsLando — APPROVED** [review]

**Comment by jcs090218** [comment]
Any update on this?

**Comment by aboe026** [comment]
Seems like the error on the failing badge `CI / test (12.x, windows-latest) (pull_request)` is
```
> Error! Error: EPERM: operation not permitted, open 'D:\a\pkg\pkg\test\test-50-public-packages\test-output.exe'
> node D:\a\pkg\pkg\lib-es5\bin.js --public-packages=* --target node14 --output ./test-output.exe ./test-x-index.js
> Status 2, expected 0
> node main.js node14
```
Not sure how my changes would have caused that regression, perhaps a flaky test? I'd also appreciate some guidance on the test structure and how they are written, they do not seem to be in any test framework that I've worked with in the past (jest, mocha, tape, etc)

**Comment by aboe026** [comment]
Can this please be reopened?

**Pull request closed without merging**
