### PR TITLE
Add cross-platform support for dot-node files

### PR DESCRIPTION
**Pull request by david-mohr**
Here's my attempt at cross-platform support for node files.

- It will try to automatically download node files using prebuild-install
- Where that's not available, one can also manually add the pre-compiled node files using the `.${platform}` file extension

This is an addon to #837.

### CODE REVIEW

**Comment by leerob** [comment]
Could you take a look at the failing tests?

**Comment by david-mohr** [comment]
@leerob yep, working on it

**Comment by david-mohr** [comment]
@leerob done, tests now pass

**Review by leerob — APPROVED** [review]
Amazing! Thank you. I will try to release again.

**Pull request merged**
