### PR TITLE
Branding change

### PR DESCRIPTION
**Pull request by Jacob-Marshall**
I changed ZEIT to Vercel

### CODE REVIEW

**Comment by igorklopov** [comment]
Great! Also `Vercel Now` -> `Vercel` please.

**Comment by Jacob-Marshall** [comment]
Ok, I've made the change

**Comment by Jacob-Marshall** [comment]
@igorklopov Is this suitable to merge?

**Comment by igorklopov** [comment]
@Jacob-Marshall thanks!

**Pull request merged**
