### PR TITLE
Bump to vercel/pkg-fetch@v3.0.2

### PR DESCRIPTION
**Pull request by jesec**

### CODE REVIEW

**Comment by erossignon** [comment]
lgtm

**Review by erossignon — APPROVED** [review]

**Review by robertsLando — APPROVED** [review]

**Comment by leerob** [comment]
Are we ready to release? Major version, correct?

**Comment by jesec** [comment]
> Are we ready to release? Major version, correct?

Yes. AFAIK there is no blocker right now and with this merged we can proceed to release.

**Comment by jesec** [comment]
Em.. I just discovered a bug (vercel/pkg-fetch#170) that prevents users from using "linuxstatic". 

We may want to wait for pkg-fetch 3.0.3.

**Comment by leerob** [comment]
Released 👍

**Pull request merged**
